apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  ports:
    - name: '9092'
      port: 9092
      targetPort: 9092
  selector:
    service: udaconnect-location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer
    spec:
      containers:
        - image: m7moxd/location-consumer
          name: udaconnect-api
          imagePullPolicy: Always
          env:
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: KAFKA_TOPIC
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-kafka-env
                  key: DB_PORT
      restartPolicy: Always
